function  speedSection = calSpeedSection(curveDistFeature)
curvespeeddata = [...
    curveDistFeature.v0_10_time;...
    curveDistFeature.v10_20_time;...
    curveDistFeature.v20_30_time;...
    curveDistFeature.v30_40_time;...
    curveDistFeature.v40_50_time;...
    curveDistFeature.v50_60_time;...
    curveDistFeature.v60_70_time;...
    curveDistFeature.v70_inf_time;...
    ];
index = zeros(3,1);
for i = 1:3
    indextemp = find(curvespeeddata(:,i)==0);
    if isempty(indextemp)
        index(i) = inf;
    else
        index(i) = indextemp(1)*10-10;
    end
end
index_sorted = sort(index);
index_sorted = [0;index_sorted];
for i = 1:length(index)
    ind = find(index_sorted==index(i));
    speedSection(i,:) = [index_sorted(ind-1),index_sorted(ind)];
end

end
